### ISSUE TITLE
opcodes/m68k-dis.c:reg_names[] differ between binutils 2.9.1 and 2.14

### ISSUE THREAD

**Issue by sezero** [cahirwpz/amigaos-binutils-2.9.1#1]
Diff between the two is:

```
 static char *const reg_names[] = {
   "%d0", "%d1", "%d2", "%d3", "%d4", "%d5", "%d6", "%d7",
-  "%a0", "%a1", "%a2", "%a3", "%a4", "%fp", "%a6", "%sp",
+  "%a0", "%a1", "%a2", "%a3", "%a4", "%a5", "%a6", "%sp",
   "%ps", "%pc"
 }
```

Which one is correct? (Or, is there some weird subtle difference
between the two that makes each is correct within their versions
as they are?.)

**Comment by tboeckel** [comment]
As far as I know "fp" (frame pointer) is a synonym for "a5", just like "sp" (stack pointer) is a synonym for "a7". Hence the difference shouldn't cause any issues.

**Comment by sezero** [comment]
OK then, thanks.
